### ISSUE TITLE
Changing spinner animation colors

### ISSUE THREAD

**Issue by ogirbla** [YeongCheon/ngx-pull-to-refresh#25]
Is there a way to change the spinner animation colors?

**Comment by YeongCheon** [comment]
That option is not currently supported.

**Comment by maxcodefaster** [comment]
You can do something like this:

```
// pull to refresh spinner
.ngx-ptr-spinner {
  filter: grayscale(1);
}
```

**Comment by lindsayevans** [comment]
You can also override the colours in the keyframe animation to match your `spinnerColor` (needs to be in your top-level `styles.scss`):

```css
.ngx-ptr-animation .ngx-ptr-path {
    animation: ngx-ptr-dash 1.4s ease-in-out infinite,
        ngx-ptr-colors-override 5.6s ease-in-out infinite !important;
}

@keyframes ngx-ptr-colors-override {
    0% {
        stroke: #3c6a1d;
    }
    100% {
        stroke: #3c6a1d;
    }
}
```
